name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-typescript:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

      - name: Lint
        id: npm-lint
        run: npm run lint

      - name: Test
        id: npm-ci-test
        run: npm run ci-test

  integration-tests:
    name: Integration Tests
    if: github.secret_source != 'None'
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
      - name: setup hx CLI
        id: setup
        uses: Hyphen/setup-hx-action@v1
        with:
          apiKey: ${{ secrets.HYPHEN_API_KEY }}
          hyphen-dev: true
      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          hxKeyFile: ${{ secrets.HYPHEN_KEY_FILE }}
          environment: development
          outputs: |-
            files
            variables
      - name: test outputs
        id: test-outputs
        run: |
          node ./integration-test.js
